"""reference back_populate

Revision ID: 20d49495cba7
Revises: 00c28f8e454a
Create Date: 2016-02-13 14:05:46.637687

"""

# revision identifiers, used by Alembic.
revision = '20d49495cba7'
down_revision = '00c28f8e454a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('responses', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
