"""user_role

Revision ID: a86422b5f39a
Revises: 9946740122ce
Create Date: 2016-02-13 12:41:50.387475

"""

# revision identifiers, used by Alembic.
revision = 'a86422b5f39a'
down_revision = '9946740122ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'advocate', 'provider'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    ### end Alembic commands ###
