"""remove service id on need

Revision ID: 08aba74e344c
Revises: 5955de3d192c
Create Date: 2017-08-25 14:07:05.760423

"""

# revision identifiers, used by Alembic.
revision = '08aba74e344c'
down_revision = '5955de3d192c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'need_ibfk_2', 'need', type_='foreignkey')
    op.drop_column('need', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'need_ibfk_2', 'need', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###
