"""provider notified needs

Revision ID: 15d569ccbee5
Revises: fdf7a2ee45a8
Create Date: 2016-09-20 01:05:47.868029

"""

# revision identifiers, used by Alembic.
revision = '15d569ccbee5'
down_revision = 'fdf7a2ee45a8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_notified',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_notified_needs',
    sa.Column('provider_notified_id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['need.id'], ),
    sa.ForeignKeyConstraint(['provider_notified_id'], ['provider_notified.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_notified_needs')
    op.drop_table('provider_notified')
    ### end Alembic commands ###
