"""service category sort

Revision ID: 368b199625d8
Revises: 9b6d9727e3ac
Create Date: 2016-08-18 23:28:18.038946

"""

# revision identifiers, used by Alembic.
revision = '368b199625d8'
down_revision = '9b6d9727e3ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'categories',
        sa.Column('sort_order', sa.Integer(), nullable=True, default=0))

    op.add_column(
        'service',
        sa.Column('sort_order', sa.Integer(), nullable=True, default=0))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'sort_order')
    op.drop_column('categories', 'sort_order')
    ### end Alembic commands ###
