"""fix fk

This may require refactoring later. I had to remove all the entries
in alert_services and user_services to accomplish this migration.

Revision ID: 3c88a5ef8db8
Revises: 7ee0d022e8d6
Create Date: 2016-08-22 22:46:17.173111

"""

# revision identifiers, used by Alembic.
revision = '3c88a5ef8db8'
down_revision = '7ee0d022e8d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'alert_services_ibfk_2', 'alert_services', type_='foreignkey')
    op.drop_index('category_id', table_name='alert_services')
    op.create_foreign_key(None, 'alert_services', 'service', ['service_id'], ['id'])
    op.drop_constraint(u'user_services_ibfk_1', 'user_services', type_='foreignkey')
    op.drop_index('category_id', table_name='user_services')
    op.create_foreign_key(None, 'user_services', 'service', ['service_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_services', type_='foreignkey')
    op.create_foreign_key(u'user_services_ibfk_1', 'user_services', 'categories', ['service_id'], ['id'])
    op.create_index('category_id', 'user_services', ['service_id'], unique=False)
    op.drop_constraint(None, 'alert_services', type_='foreignkey')
    op.create_foreign_key(u'alert_services_ibfk_2', 'alert_services', 'categories', ['service_id'], ['id'])
    op.create_index('category_id', 'alert_services', ['service_id'], unique=False)
    ### end Alembic commands ###
