"""sort order not null

Revision ID: 3e7e65c44fc2
Revises: 368b199625d8
Create Date: 2016-08-21 03:05:06.778204

"""

# revision identifiers, used by Alembic.
revision = '3e7e65c44fc2'
down_revision = '368b199625d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from _15thnight.models import Category, Service


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        Category.__table__.update()
        .where(Category.__table__.c.sort_order == None)
        .values(**{'sort_order': 0})
    )
    op.alter_column(
        'categories', 'sort_order', existing_type=sa.INTEGER(),
        nullable=False)

    op.execute(
        Service.__table__.update()
        .where(Service.__table__.c.sort_order == None)
        .values(**{'sort_order': 0})
    )
    op.alter_column(
        'service', 'sort_order', existing_type=sa.INTEGER(),
        nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service', 'sort_order', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'categories', 'sort_order', existing_type=sa.INTEGER(), nullable=True)
    ### end Alembic commands ###
