"""reset password

Revision ID: 4aa97e34f066
Revises: 97dd03d6ec76
Create Date: 2016-08-16 18:11:42.717344

"""

# revision identifiers, used by Alembic.
revision = '4aa97e34f066'
down_revision = '97dd03d6ec76'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'reset_created_at')
    ### end Alembic commands ###
