"""need resolve notes message selected

Revision ID: 6240c2fc9bbd
Revises: 4060ea26d835
Create Date: 2016-09-27 12:57:17.667251

"""

# revision identifiers, used by Alembic.
revision = '6240c2fc9bbd'
down_revision = '4060ea26d835'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('resolve_message', sa.Text(), nullable=True))
    op.add_column('need', sa.Column('resolve_notes', sa.Text(), nullable=True))
    op.add_column('need_provided', sa.Column('selected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need_provided', 'selected')
    op.drop_column('need', 'resolve_notes')
    op.drop_column('need', 'resolve_message')
    ### end Alembic commands ###
