"""services

Revision ID: 9b6d9727e3ac
Revises: 4aa97e34f066
Create Date: 2016-08-17 21:37:10.523179

"""

# revision identifiers, used by Alembic.
revision = '9b6d9727e3ac'
down_revision = '4aa97e34f066'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.drop_table('alert_categories')
    op.drop_table('user_categories')
    op.create_table(
        'alert_services',
        sa.Column('alert_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    )
    op.create_table(
        'user_services',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_services')
    op.drop_table('user_services')
    op.create_table(
        'alert_categories',
        sa.Column('alert_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['category_id.id'], ),
    )
    op.create_table(
        'user_categories',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['category_id.id'], ),
    )
    ### end Alembic commands ###
