"""services

Revision ID: 9b6d9727e3ac
Revises: 4aa97e34f066
Create Date: 2016-08-17 21:37:10.523179

"""

# revision identifiers, used by Alembic.
revision = '9b6d9727e3ac'
down_revision = '4aa97e34f066'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('alert_categories', 'category_id',
        existing_type=sa.Integer(), new_column_name='service_id')
    op.alter_column('user_categories', 'category_id',
        existing_type=sa.Integer(), new_column_name='service_id')
    op.rename_table('alert_categories', 'alert_services')
    op.rename_table('user_categories', 'user_services')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('alert_services', 'alert_categories')
    op.rename_table('user_services', 'user_categories')
    op.alter_column('alert_categories', 'service_id',
        existing_type=sa.Integer(), new_column_name='category_id')
    op.alter_column('user_categories', 'service_id',
        existing_type=sa.Integer(), new_column_name='category_id')
    op.drop_table('service')
    ### end Alembic commands ###
