"""alert gender age

Revision ID: a6fbbe49d0bd
Revises: 5d5b3a73cb2e
Create Date: 2016-02-13 19:34:00.218391

"""

# revision identifiers, used by Alembic.
revision = 'a6fbbe49d0bd'
down_revision = '5d5b3a73cb2e'
branch_labels = None
depends_on = None

from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
import sqlalchemy as sa

try:
    from config import DATABASE_URL
except:
    from configdist import DATABASE_URL

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    gender_column = sa.Column('gender', sa.Enum('male', 'female', 'unspecified'))
    if DATABASE_URL[:8] == 'postgres':
        gender_enum = ENUM('male', 'female', 'unspecified', name='alert_gender')
        gender_enum.create(op.get_bind(), checkfirst=False)
        gender_column = sa.Column('gender', gender_enum)
    op.add_column('alerts', sa.Column('age', sa.Integer()))
    op.add_column('alerts', gender_column)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'gender')
    op.drop_column('alerts', 'age')
    ### end Alembic commands ###
