"""alert, provider FKs on pledge; service details on need

Revision ID: c16b76d57fb5
Revises: 6240c2fc9bbd
Create Date: 2017-06-02 16:24:43.354703

"""

# revision identifiers, used by Alembic.
revision = 'c16b76d57fb5'
down_revision = '6240c2fc9bbd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('category_description', sa.Text(), nullable=True))
    op.add_column('need', sa.Column('category_name', sa.String(length=255), nullable=True))
    op.add_column('need', sa.Column('service_description', sa.Text(), nullable=True))
    op.add_column('need', sa.Column('service_name', sa.String(length=255), nullable=True))
    op.add_column('need_provided', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.add_column('need_provided', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'need_provided', 'users', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'need_provided', 'alerts', ['alert_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'need_provided', type_='foreignkey')
    op.drop_constraint(None, 'need_provided', type_='foreignkey')
    op.drop_column('need_provided', 'provider_id')
    op.drop_column('need_provided', 'alert_id')
    op.drop_column('need', 'service_name')
    op.drop_column('need', 'service_description')
    op.drop_column('need', 'category_name')
    op.drop_column('need', 'category_description')
    ### end Alembic commands ###
