"""need resolve history

Revision ID: d50de15f6310
Revises: 4060ea26d835
Create Date: 2016-09-24 17:55:18.635970

"""

# revision identifiers, used by Alembic.
revision = 'd50de15f6310'
down_revision = '4060ea26d835'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('need_resolve_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['need_id'], ['need.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('need_resolve_history')
    ### end Alembic commands ###
