"""one response per provider per alert

Revision ID: e4ff5a3a80cb
Revises: 7ee0d022e8d6
Create Date: 2016-08-25 21:08:41.248802

"""

# revision identifiers, used by Alembic.
revision = 'e4ff5a3a80cb'
down_revision = '7ee0d022e8d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'responses', 'alert_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        'responses', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(
        '_provider_response_uc', 'responses', ['alert_id', 'user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_provider_response_uc', 'responses', type_='unique')
    op.alter_column(
        'responses', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'responses', 'alert_id', existing_type=sa.INTEGER(), nullable=True)
    ### end Alembic commands ###
