"""need and need provided table

Revision ID: fdf7a2ee45a8
Revises: 7ee0d022e8d6
Create Date: 2016-09-12 21:11:01.881072

"""

# revision identifiers, used by Alembic.
revision = 'fdf7a2ee45a8'
down_revision = '7ee0d022e8d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('need_provided',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['need.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alert_services')
    op.drop_column('responses', 'message')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('message', mysql.TEXT(), nullable=True))
    op.create_table('alert_services',
    sa.Column('alert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], [u'alerts.id'], name=u'alert_services_ibfk_1'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], name=u'alert_services_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('need_provided')
    op.drop_table('need')
    ### end Alembic commands ###
